databases:
  - name: fotobook-db
    databaseName: fotobook
    user: fotobook
    plan: free
    region: singapore

services:
  - type: web
    name: fotobook-web
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fotobook-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      # - key: SOLID_QUEUE_IN_PUMA
      #   value: "true"

      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production

      - key: SECRET_KEY_BASE
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "0"
